---
title: "Untitled"
output: html_document
date: "2023-01-08"
---
```{r}
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
library(janitor)
library(spatialreg)
library(tidyverse)
library(readxl)
library(spdep)
library(plotly)
library(RColorBrewer)
```


```{r}
# Use read_sf() function to load shape file 
Birminghamshp <- read_sf(here::here("Birmingham","Bi.shp"))

# LSOA's spatial configuration and hierarchy can be visualized by creating an empty map
tmap_mode("plot")+
  tm_shape (Birminghamshp)+tm_polygons(col = NA, alpha = 0.5)+ tmap_options(check.and.fix = TRUE)
```
```{r}
# Read xlsx files using read.xlsx
F_IMD_ed_child <- read_xlsx(here::here("Birmingham_Fin_Menillness_IMD_Child.xlsx"))%>%
  #Clean the header line, remove the unreadable R symbols and convert all to lowercase
  janitor::clean_names()

# Merge data to Birminghamshp uniquely by using ’losa‘ code column
spatialdatafile <- merge(Birminghamshp, F_IMD_ed_child, by.x = "lsoa11cd", by.y = "lsoa2011")


#View the distribution of financially vulnerable rank in the Birmingham area 
plot_fvrank <- tm_shape(spatialdatafile) + tm_fill("fv_rank", style = "quantile", n = 5, palette = "Greens") +
tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
tm_compass(position = c("right", "bottom")) +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(frame = FALSE, legend.title.size = 1.3, legend.text.size = 0.7) 

# plot the image object
plot_fvrank

#View the distribution of IMDScore in the Birmingham area 
plot_imd <- tm_shape(spatialdatafile) + tm_fill("imd_score", style = "quantile", n = 5, palette = "Purples") +
tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
tm_compass(position = c("right", "bottom")) +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(frame = FALSE, legend.title.size = 1.3, legend.text.size = 0.7)

# plot the image object
plot_imd

#View the distribution of Number of families receiving child tax credit in the Birmingham area 
plot_ctc <- tm_shape(spatialdatafile) + tm_fill("number_ctc_families", style = "quantile", n = 5, palette = "Reds") +
tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
tm_compass(position = c("right", "bottom")) +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(frame = FALSE, legend.title.size = 1.3, legend.text.size = 0.7)
plot_ctc

#View the distribution of Education, skills and training deprivation Score in the Birmingham area 
plot_estScore <- tm_shape(spatialdatafile) + tm_fill("est_score", style = "quantile", n = 5, palette = "Blues") +
tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
tm_compass(position = c("right", "bottom")) +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(frame = FALSE, legend.title.size = 1.3, legend.text.size = 0.7)
plot_estScore
```

```{r}
summary(F_IMD_ed_child)
matrix=var(F_IMD_ed_child)

#Visualization of data statistics
model <-lm(est_score ~ imd_score + fv_rank + number_ctc_families, data=spatialdatafile)
par(mfrow=c(2,2))
plot(model)

# lm() function builds a regression model and stores model output into the object 'modelMLR'
modelMLR <- lm(log10(est_score) ~ log10(imd_score) + log10(fv_rank) + log10(number_ctc_families), data = spatialdatafile)

#Scientific counting method
options(scipen = 7)

#Display the result output
summary(modelMLR)
```
```{r}
#Extract the residuals and insert them into the data set and read them
spatialdatafile$RESIDUALS <- modelMLR$residuals

#Showing the distribution of data for a more visual representation in the map
summary(spatialdatafile$RESIDUALS)

#Showing residual maps of the Birmingham area
tm_shape(spatialdatafile) + tm_fill("RESIDUALS", style = "cont", midpoint = 0, palette = "-RdBu") +
tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
tm_compass(position = c("right", "top")) +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(frame = FALSE, legend.title.size = 0.5, legend.text.size = 0.5)
```
```{r}
#Guarantee that each line has a unique number
spatialdatafile$ROWNUM <- 1:nrow(spatialdatafile)

# Spatialize the spatialdatafile for subsequent content
spatialdatafile_2.0 <- as(spatialdatafile, "Spatial")

#Create spatial weight matrix
Weights <- poly2nb(spatialdatafile_2.0, row.names = spatialdatafile_2.0$ROWNUM)
WeightsMatrix <- nb2mat(Weights, style='B')
Residual_WeightMatrix <- mat2listw(WeightsMatrix , style='W')

#Use lm.morantest() to view and display useful information
lm.morantest(modelMLR, Residual_WeightMatrix, alternative="two.sided")
```
```{r}
# Fit model using lagsarlm()
# reuse spatial weight matrix created earlier as an object called "Residual_WeighMatrix" 
modelSLY <- lagsarlm(log10(est_score) ~ log10(imd_score) + log10(fv_rank) + log10(number_ctc_families), data = spatialdatafile_2.0, Residual_WeightMatrix)

# Report regression results showing interesting data information, e.g. AIC, p-value, etc.
summary(modelSLY)

```
```{r}
# The spatial lag model extracts the residuals and saves them in the dataset.
spatialdatafile$RESID_SLY <- modelSLY$residuals

# Global Moran's I Analysis
moran.mc(spatialdatafile$RESID_SLY, Residual_WeightMatrix, 1000, zero.policy = T)

```
```{r}
# Generating residual plots for spatial lag models
tm_shape(spatialdatafile) + tm_fill("RESID_SLY", style = "cont", midpoint = 0, palette = "-RdBu") +
    tm_compass(position = c("right", "top")) +
    tm_scale_bar(position = c("left", "bottom")) +
    tm_layout(frame = FALSE, legend.title.size = 0.5, legend.text.size = 0.5)
```
```{r}
# Generate information to facilitate the interpretation of results

Weights_2.0 <- as(Residual_WeightMatrix, "CsparseMatrix")
trMC <- trW(Weights_2.0, type="MC")
summary(impacts(modelSLY, tr = trMC, R=100), zstats=TRUE)


```
```{r}
#Spatial error modelling with errorsrlm()
modelSER <- errorsarlm(log10(est_score) ~ log10(imd_score) + log10(fv_rank) + log10(number_ctc_families), data = spatialdatafile_2.0, Residual_WeightMatrix)

#Use summary() to interpret the results of the report
summary(modelSER)
```
```{r}
# Residuals are extracted for the spatial error model and saved in the dataset.
spatialdatafile$RESID_SER <- modelSER$residuals

# Global Moran's I Analysis
moran.mc(spatialdatafile$RESID_SER, Residual_WeightMatrix, 1000, zero.policy = T)

# generate the map
tm_shape(spatialdatafile) + tm_fill("RESID_SER", style = "cont", midpoint = 0, palette = "-RdBu") +
    tm_compass(position = c("right", "top")) +
    tm_scale_bar(position = c("left", "bottom")) +
    tm_layout(frame = FALSE, legend.title.size = 0.5, legend.text.size = 0.5)
```
